### ISSUE TITLE
Avoid having anything that doesn't export core function in core directory

### ISSUE THREAD

**Issue by timbrock** [kiln/template-skeleton#2]
Personal preference, of course, (and feel free to ignore) but I feel the init file shouldn't be in the core directory.

**Comment by daanlouter** [comment]
Fine by me! Done in https://github.com/kiln/template-skeleton/commit/73af5921e7dbdf615d489d40bce43fa474546323

**Comment by timbrock** [comment]
FWIW, I actually meant in a different sub-directory. But anything that feels logical to you is fine by me.

**Comment by daanlouter** [comment]
I don't feel strongly, I only think we should cut a good balance between good starting point for consistency, and not being too complex. What would you suggest for sub directory?

**Comment by timbrock** [comment]
I tend to do (YMMV)...
src/
-- core/ (data, state, draw, update)
-- lib/ (process_data, init, other stuff used by core functions)
-- utils/ (useful generic functions that might be used in a number of places)
